### ISSUE TITLE
freshly installing with Package Manager doesn't extract default settings

### ISSUE THREAD

**Issue by mrexodia** [ar7bd/sublime-gitextensions#2]

**Comment by LinuxDevon** [comment]
I haven't seen any movement on this issue. I forked this project and fixed a bug in it. I submitted a PR.

I don't know if that addressed this issue. I don't know if I have narrowed down the issue with this yet. From what I have seen all other repos do it the same way. 

My repo was just submitted to the Package Control repo and am hopeful this might address this issue. If not a way to get around this is to drop the settings and hard code them.
https://github.com/LinuxDevon/sublime-gitextensions

**Comment by ar7bd** [comment]
Merged PR #3

**Comment by ar7bd** [comment]
@LinuxDevon thanks for providing the PR!
